### ISSUE TITLE
Link to Travis or Circle CI samples

### ISSUE THREAD

**Issue by ghost** [rub8n/VSTSCDSample#1]
This repo is currently linked to from the official Microsoft CodePush documentation. As a developer I'd like to see a list of samples for Travis and Circle so I don't have to buy into Microsoft products.

**Comment by rub8n** [comment]
@jhabdas Thanks for the feedback! I'm no longer working with the CodePush team but I'll pass along the feedback. 

In the meantime, this might help: https://github.com/mondora/code-push-travis-cli

**Comment by ghost** [comment]
Thanks @rub8n. I sent them some feedback via the NPS module in their doc. A little more feedback couldn't hurt though. Thanks!
